name: build-deploy-staging
on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]
jobs:
  build-staging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo 'hello world'
