name: build-deploy-staging
on:
  pull-request:
    branches:
      - '*'
jobs:
  build-staging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo 'hello world'
